version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=tastyeats
    ports:
      - "5432:5432"
    volumes:
      - ./db/create_dbs.sql:/docker-entrypoint-initdb.d/create_dbs.sql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tastynet

networks:
  tastynet:
